#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["Server/Server.csproj", "Server/"]
RUN dotnet restore "Server/Server.csproj"
COPY . .
WORKDIR "/src/Server"
RUN dotnet build "Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV APP_ConnectionStrings__App=server=localhost;port=3306;database=App;uid=root;password=test
ENV APP_JwtOptions__Secret=
ENV APP_JwtOptions__Key=
ENV APP_KartriderApiKey=
ENV APP_Sentry__Dsn=

ENTRYPOINT ["dotnet", "Server.dll"]